### ISSUE TITLE
private_pub vs danthes

### ISSUE THREAD

**Issue by fluxsaas** [simonoff/danthes#1]
Hey,

i'm just wondering what problem are you solving with this fork? Meaning, Why is your fork "better" than private_pub ?

thanks

**Comment by sadfuzzy** [comment]
+1

**Comment by sadfuzzy** [comment]
@fluxsaas , try https://github.com/twetzel/private_pub

**Comment by fluxsaas** [comment]
yeah. i already switched to sth. else :)

**Comment by sadfuzzy** [comment]
@fluxsaas, "sth"?

**Comment by fluxsaas** [comment]
have a look at:

https://github.com/stevegraham/slanger
